### ISSUE TITLE
onemap 

### ISSUE THREAD

**Issue by radhakrishnanganapathy** [sadhilchhabra/Singapore_Resale_Flat_Prices_Predicting#1]
hi , https://developers.onemap.sg not working

Getting this error :
ConnectionError: HTTPSConnectionPool(host='developers.onemap.sg', port=443): Max retries exceeded with url: /commonapi/search?searchVal=Jurong%20East%20MRT%20Station&returnGeom=Y&getAddrDetails=Y (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000277D5C23B30>: Failed to resolve 'developers.onemap.sg' ([Errno 11001] getaddrinfo failed)"))

![Screenshot (250)](https://github.com/sadhilchhabra/Singapore_Resale_Flat_Prices_Predicting/assets/85297693/a25e438b-4e60-40f6-b563-3695b3803773)

**Comment by sadhilchhabra** [comment]
The domain has now been updated to use https://www.onemap.gov.sg/. Additionally, the new URL for sending the GET request is as follows:

https://www.onemap.gov.sg/api/common/elastic/search?searchVal='+str(query_address)+'&returnGeom=Y&getAddrDetails=Y&pageNum=1

Replace query_address as per your requirements
